app/models.py
from app import db, login
from flask_login import UserMixin
import random

user_attendance = db.Table('user_attendance',
                            db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
                            db.Column('attendance_id', db.Integer, db.ForeignKey('attendance.id')))

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(64), index=True)
    last_name = db.Column(db.String(64), index=True)
    email = db.Column(db.String(120), index=True, unique=True)
    attendance = db.relationship('Attendance', secondary=user_attendance, backref=db.backref('attendees', lazy='dynamic'))
    is_admin = db.Column(db.Boolean, index=True, default=False)

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class Attendance(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String, index=True, unique=True)
    start_time = db.Column(db.DateTime, index=True)
    end_time = db.Column(db.DateTime, index=True)

    def generate_random_code(length):
        characters = "abcdefghijklmnopqrstuvwxyz1234567890"
        code = ""
        for _ in range(length):
            code += random.choice(characters)
        return code

    def random_code(length):
        code = Attendance.generate_random_code(length)
        while Attendance.query.filter_by(code=code).first():
            code = Attendance.generate_random_code(length)
        return code
            

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField, TimeField
from wtforms.validators import DataRequired

class AttendanceForm(FlaskForm):
    code = StringField('Code', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_moment import Moment

app = Flask(__name__)
app.config.from_object('config')
db = SQLAlchemy(app)
migrate = Migrate(app, db)
moment = Moment(app)

login = LoginManager(app)
login.login_view = 'auth.login'
login.login_message = None

from app.models import User, Attendance
db.create_all()
db.session.commit()

from app.routes import main, attendance, auth
app.register_blueprint(main.bp)
app.register_blueprint(attendance.bp)
app.register_blueprint(auth.bp)

app/routes/attendance.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort, session
from flask_login import current_user, login_required
from app import db
from app.forms import AttendanceForm
from app.models import Attendance
from app.utils import is_valid_attendance
import json

bp = Blueprint('attendance', __name__)

@bp.route('/here')
def attendance_redirect():
    return redirect(url_for('attendance.attendance'))

@bp.route('/attendance', methods=['GET', 'POST'])
@login_required
def attendance():
    form = AttendanceForm()
    if form.validate_on_submit():
        code = form.code.data
    else:
        code = request.args.get('code')
    if code:
        attendance = Attendance.query.filter_by(code=code).first()
        if attendance and is_valid_attendance(attendance):
            if not attendance in current_user.attendance:
                attendance.attendees.append(current_user)
                db.session.commit()
            session['attendance_success'] = True
            return redirect(url_for('attendance.success'))
        flash("The code you entered is invalid.")
        return redirect(url_for('attendance.attendance'))
    return render_template('attendance/attendance.html', form=form)

@bp.route('/attendance/success')
def success():
    if not session.get('attendance_success'):
        return redirect(url_for('attendance.attendance'))
    session.pop('attendance_success', None)
    return render_template('attendance/success.html')

@bp.route('/attendance/admin', methods=['GET', 'POST'])
@login_required
def admin():
    if not current_user.is_admin:
        abort(403)
    attendances = Attendance.query.order_by(Attendance.end_time.desc()).all()
    return render_template('attendance/admin.html', attendances=attendances, len=len, is_valid_attendance=is_valid_attendance)

@bp.route('/attendance/create', methods=['POST'])
@login_required
def create_attendance():
    if not current_user.is_admin:
        abort(403)
    res = request.get_data("data")
    data = json.loads(res)
    code = data.get("code")
    start_time = data.get("start_time")
    end_time = data.get("end_time")
    
    if not (start_time and end_time):
        return "Missing or empty fields."
    if not code:
        code = Attendance.random_code(length=6)

    attendance = Attendance(code=code, start_time=start_time, end_time=end_time)
    if Attendance.query.filter_by(code=code).first() is None:
        db.session.add(attendance)
        db.session.commit()
        return "Attendance code created successfully."
    return "Attendance code already exists."

@bp.route('/attendance/<code>/attendees')
@login_required
def attendees(code):
    if not current_user.is_admin:
        abort(403)
    attendance = Attendance.query.filter_by(code=code).first_or_404()
    return render_template('attendance/attendees.html', attendance=attendance)

@bp.route('/attendance/<code>/display')
@login_required
def display(code):
    if not current_user.is_admin:
        abort(403)
    attendance = Attendance.query.filter_by(code=code).first_or_404()
    return render_template('attendance/display.html', attendance=attendance)

app/routes/auth.py
from flask import Blueprint, redirect, render_template, url_for, session, flash, request
from werkzeug.urls import url_parse
from app import db
from app.oauth import get_auth_url, get_access_token, get_user_info
from app.models import User
from flask_login import current_user, login_user, logout_user

bp = Blueprint('auth', __name__)


@bp.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    session['next'] = request.args.get('next')
    return render_template('auth/login.html')

@bp.route('/auth/google')
def authorize():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    return redirect(get_auth_url())

@bp.route('/auth/callback')
def callback():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    
    access_token = get_access_token()
    if access_token == 'error':
        flash("Invalid credentials. Please try again.", "error")
        return redirect(url_for('auth.login'))
    
    user_info = get_user_info(access_token)
    user = User.query.filter_by(email=user_info['email']).first()
    if user_info['email'].split('@')[1] != "wrdsb.ca":
        flash("Please login with your school account.")
        return redirect(url_for('auth.login'))

    if not user:
        user = User(first_name=user_info['given_name'], 
                    last_name=user_info['family_name'], 
                    email=user_info['email'])
        db.session.add(user)
        db.session.commit()

    login_user(user, remember=True)
    next_page = session.get('next')
    if not next_page or url_parse(next_page).netloc != '':
        next_page = url_for('main.index')
    session.pop('next', None)
    return redirect(next_page)

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

app/routes/main.py
from flask import Blueprint, render_template
from app.constants import faq

bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    return render_template('main/index.html', faq=faq, home=True)

app/templates/attendance/admin.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/attendance.css') }}">
{% endblock %}

{% block content %}
<div class="main-left">
    <h2>Create a new attendance code</h2>
    <p style="margin-top: 10px;">Leave blank for random code</p>
    <form id="form">
        <p>
            <input id="code" class="code-input" placeholder="Attendance code" autocomplete="off" spellcheck="false">
        </p>
        <p>
            <input id="date" type="date">
        </p>
        <p>
            <input id="start_time" type="time">
            <input id="end_time" type="time">
        </p>
        <p>
            <button id="submit" class="form-submit admin-submit">Create</button>
        </p>
        <div id="errors" class="errors">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <p class="form-error">{{ message }}</p>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
    </form>
    <div class="attendance-container">
        <h2>Attendance codes</h2>
        {% if attendances %}
            <p class="attendance-row">
                <span class="row-heading display">Display</span>
                <span class="row-heading code">Attendance Code</span>
                <span class="row-heading date">Start Date</span>
                <span class="row-heading date">End Date</span>
                <span class="row-heading attendees">Attendees</span>
                <span class="row-heading invalid">Status</span>
            </p>
            {% for attendance in attendances %}
                <p class="attendance-row">
                    <a class="display" href="{{ url_for('attendance.display', code=attendance.code) }}">
                        <i class="fa-solid fa-arrow-up-right-from-square"></i>
                    </a>
                    <span class="code">{{ attendance.code }}</span>
                    <span class="date">{{ moment(attendance.start_time).format('MMM D h:mma') }}</span>
                    <span class="date">{{ moment(attendance.end_time).format('MMM D h:mma') }}</span>
                    <a class="attendees" href="{{ url_for('attendance.attendees', code=attendance.code) }}">
                        <i class="fa-solid fa-user"></i> {{ len(attendance.attendees.all()) }}
                    </a>
                    {% if is_valid_attendance(attendance) %}
                    <span class="valid">Valid</span>
                    {% else %}
                    <span class="invalid">Expired</span>
                    {% endif %}
                </p>
            {% endfor %}
        {% else %}
            <p>No attendances recorded.</p>
        {% endif %}
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

<script type="text/javascript">
    const addError = (message) => {
        $("#errors").append("<p class='form-error'>" + message + "</p>");
    }

    const utcDate = (date, time) => {
        let resDate = new Date(date + ' ' + time);
        return resDate.toUTCString();
    }

    const createAttendanceCode = () => {
        let date = $("#date").val();
        let start_time = utcDate(date, $("#start_time").val());
        let end_time = utcDate(date, $("#end_time").val());

        if (start_time === "Invalid Date" || end_time === "Invalid Date") {
            addError("Missing or empty fields");
            return;
        }

        $.ajax({
            type: 'POST',
            url: "/attendance/create",
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify({
                code: $("#code").val(),
                start_time: start_time,
                end_time: end_time,
            }),
            success: (message) => {
                console.log(message)
                if (message === "Attendance code created successfully.") {
                    location.reload(true);
                } else {
                    addError(message);
                }
            },
        })
    }

    const pad = (num) => {
        if (num >= 10) return num;
        return '0' + num;
    }

    const fillDates = () => {
        let today = new Date();
        let currentDate = today.getFullYear() + '-' + pad(today.getMonth()+1) + '-' + pad(today.getDate());
        let startTime = pad(today.getHours()) + ':' + pad(today.getMinutes());
        let endTime = pad((today.getHours() + 2) % 24) + ':' + pad(today.getMinutes());
        document.getElementById("date").value = currentDate;
        document.getElementById("start_time").value = startTime;
        document.getElementById("end_time").value = endTime;       
    }

    fillDates();
    $("#submit").click(createAttendanceCode);
    $("#form").submit((e) => e.preventDefault());
</script>
{% endblock %}

app/templates/attendance/attendance.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/attendance.css') }}">
{% endblock %}

{% block content %}
<div class="main">
    <h2>Attendance</h2>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        {{ form.code(class_="code-input", placeholder="Attendance code", autocomplete="off") }}
        <div class="errors">
            {% for error in form.code.errors %}
                <p class="form-error-centered">{{ error }}</p>
            {% endfor %}
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <p class="form-error-centered">{{ message }}</p>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <p>{{ form.submit(class_="form-submit") }}</p>
    </form>
</div>
{% endblock %}

app/templates/attendance/attendees.html
<div>
    {% for attendee in attendance.attendees %}
        <p>{{ attendee.first_name }} {{ attendee.last_name }}</p>
    {% endfor %}
</div>

app/templates/attendance/display.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/attendance.css') }}">
{% endblock %}

{% block content %}
<div class="main">
    <p class="attendance-instructions">
        Enter the attendance code at <br><a href="{{ url_for('attendance.attendance_redirect') }}">{{ url_for('attendance.attendance_redirect', _external=True) }}</a>
    </p>
    <div class="display-attendance">
        <p class="display-code {% if attendance.code|length > 6 %}display-code-small{% endif %}">{{ attendance.code }}</p>
        <div class="qr-code">
            <img src="https://api.qrserver.com/v1/create-qr-code/?size=200x200&data={{ url_for('attendance.attendance', code=attendance.code, _external=True) }}">
        </div>
    </div>
</div>
{% endblock %}

app/templates/attendance/index.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/attendance.css') }}">
{% endblock %}

{% block content %}
<div class="main">
    <h2>Attendance</h2>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        {{ form.code(class_="code-input", placeholder="Attendance code", autocomplete="off") }}
        <div class="errors">
            {% for error in form.code.errors %}
                <p class="form-error">{{ error }}</p>
            {% endfor %}
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <p class="form-error">{{ message }}</p>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <p>{{ form.submit(class_="form-submit") }}</p>
    </form>
</div>
{% endblock %}

app/templates/attendance/success.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/attendance.css') }}">
{% endblock %}

{% block content %}
<div class="main">
    <h2>The attendance code you submitted is valid.</h2>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WCI Computer Science</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block styles %}{% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
</head>

<body>
    {% if not home %}
    <nav class="nav-transparent">
        <div class="nav-links">
            <div class="nav-top">
                <a href="{{ url_for('main.index') }}" class="nav-logo">>WCI_</a>
            </div>
        </div>
        {% if current_user.is_authenticated %}
        <p class="user">
            Logged in as {{ current_user.first_name }} {{ current_user.last_name }}
            {% if current_user.is_admin %}
                (<a href="{{ url_for('attendance.admin' )}}">Admin</a>)
            {% endif %} - 
            <a href="{{ url_for('auth.logout') }}">Log out</a>
        </p>
        {% endif %}
    </nav>
    {% endif %}
    {% block content %}{% endblock %}
    {{ moment.include_moment() }}
    {% block scripts %}{% endblock %}
</body>

app/templates/includes/footer.html
<div id="footer">
    <p>>WCI_</p>
    <div class="footer-links">
        <div class="footer-left">
            <a class="classroom" href="https://classroom.google.com/c/MTY1NzAzMDQzNjJa?cjc=c2prjk3" target="_blank" rel="noopener noreferrer">
                <i class="fa-solid fa-users-rectangle"></i>
                Classroom
            </a>
            <a class="instagram" href="https://www.instagram.com/wci_computer_science/" target="_blank" rel="noopener noreferrer">
                <i class="fa-brands fa-instagram"></i>
                Instagram
            </a>
        </div>
        <div class="footer-right">
            <a href="">Home</a>
            <a href="{{ url_for('attendance.attendance') }}">Attendance</a>
        </div>
    </div>
    <div class="footer-rights">
        <p>Copyright © 2023 WCI Computer Science</p>
    </div>
</div>

app/templates/main/index.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock %}

{% block content %}
<nav class="nav-transparent">
    <div class="nav-links">
        <div class="nav-top">
            <a href="" class="nav-logo">>WCI_</a>
            <button class="hamburger">
                <i class="fa-solid fa-bars"></i>
            </button>
        </div>
        <div class="section-links">
            <a href="#about">About</a>
            <a href="#faq">FAQ</a>
            <a href="{{ url_for('attendance.attendance') }}">Attendance</a>
        </div>
    </div>
    <div class="nav-socials">
        <div class="social-icons">
            <a class="classroom" href="https://classroom.google.com/c/MTY1NzAzMDQzNjJa?cjc=c2prjk3" target="_blank" rel="noopener noreferrer">
                <i class="fa-solid fa-users-rectangle"></i>
            </a>
            <a class="instagram" href="https://www.instagram.com/wci_computer_science/" target="_blank" rel="noopener noreferrer">
                <i class="fa-brands fa-instagram"></i>
            </a>
        </div>
        <a class="nav-join-button" href="https://classroom.google.com/c/MTY1NzAzMDQzNjJa?cjc=c2prjk3" target="_blank" rel="noopener noreferrer">Join</a>
    </div>
</nav>

<div id="landing">
    <p class="meeting-time">Wednesdays from 2:30 - 4:00pm · Rm 418, 422, 424</p>
    <h1>Computer Science Club</h1>
    <p class="school">Waterloo Collegiate Institute</p>
    <p class="tagline">A community for <b>anyone</b> interested in <br><span class="typing-animation"></span></p>
    <a class="landing-button" href="https://classroom.google.com/c/MTY1NzAzMDQzNjJa?cjc=c2prjk3" target="_blank" rel="noopener noreferrer">Join our Classroom →</a>
    <div class="landing-gradient"></div>
    <div class="landing-image"></div>
</div>

<div id="about">
    <div class="about-text">
        <p id="about-header">> Learn more about computer science, software development, algorithms, and much more in our weekly meetings_</p>
        <p>You'll improve your problem-solving skills, hone your programming skills, and gain valuable insight into what it's like studying computer science or working in the tech industry. We have a beginner and advanced class, so you'll learn something no matter what your current skill level is.</p>
        <p>Feel free to stop by at one of our meetings on Wednesdays in Room 418!</p>
    </div>
    <div class="app-window">
        <div class="window-buttons">
            <div class="red"></div>
            <div class="yellow"></div>
            <div class="green"></div>
        </div>
        <h2>2023-24</h2>
        <ul class="checkbox">
            <li>workshops on software dev + tech</li>
            <li>competitions (with prizes)</li>
            <li>field trips to tech companies</li>
            <li>internship opportunities</li>
            <li>guest speakers</li>
        </ul>
        <ul class="green-check">
            <li>Beginner: coding basics in Python</li>
            <li>Advanced: algorithms + data structures</li>
        </ul>
    </div>
</div>

<div id="faq">
    <h2>Frequently asked questions</h2>
    {% for question in faq %}
        <input id="faq{{ loop.index }}" type="checkbox">
        <label for="faq{{ loop.index }}" class="faq-container">
            <p class="faq-heading">
                <span class="faq-arrow">></span>
                {{ question.question }}
            </p>
            <div class="faq-body">
                <p class="faq-text">{{ question.answer }}</p>
            </div>
        </label>
    {% endfor %}
</div>

<div id="contact">
    <h2>Any questions?</h2>
    <p>Reach out to us through <button id="email">email</button></p>
    <div class="contact-emails">
        <p>
            <a href="mailto:lauc5177@wrdsb.ca">Ching Lam</a>
            <a href="mailto:yangm0242@wrdsb.ca">Matthew</a>
            <a href="mailto:liny5987@wrdsb.ca">Yinuo</a>
        </p>
        <p>
            <a href="mailto:zhaoj1085@wrdsb.ca">Jonathan</a>
            <a href="mailto:yuanv7924@wrdsb.ca">Vivian</a>
        </p>
    </div>
    <a class="classroom" href="https://classroom.google.com/c/MTY1NzAzMDQzNjJa?cjc=c2prjk3" target="_blank" rel="noopener noreferrer">
        <i class="fa-solid fa-users-rectangle"></i>
        Classroom
    </a>
    <a class="instagram" href="https://www.instagram.com/wci_computer_science/" target="_blank" rel="noopener noreferrer">
        <i class="fa-brands fa-instagram"></i>
        Instagram
    </a>
</div>

{% include "includes/footer.html" %}
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>

<script>
    var typed = new Typed(".typing-animation", {
        strings: ["programming", "problem-solving", "technology"],
        typeSpeed: 70,
        backSpeed: 40,
        smartBackspace: false,
        loop: true,
    });
</script>
{% endblock %}